import type { Metadata } from "next"
import Link from "next/link"
import Image from "next/image"

export const metadata: Metadata = {
  title: "Build with LuckyMarkets | UpForge",
  description: "Explore LuckyMarkets, a finance education and market-tools project, its product direction, contributor tracks and application process.",
  alternates: { canonical: "https://upforge.org/projects/luckymarkets" },
}

const roles = [
  { group: "Product & Engineering", roles: ["Frontend / Full-stack Developer", "Fintech & Product Engineer", "Python / Data Engineer", "AI & Automation Developer", "Mobile App Developer", "QA / Product Tester"], note: "Potential product work includes IPO trackers and calendars, IPO research and probability-style data tools, company expansion pages, market dashboards, portfolio utilities and data pipelines. Features will be scoped around reliable sources and feasibility." },
  { group: "Markets & Research", roles: ["Equity / Market Research Associate", "IPO Researcher", "Financial Content Analyst", "Portfolio Research Associate", "Market Data Researcher"], note: "Research is educational and source-led. No guaranteed returns, personalized investment advice or unsupported stock calls." },
  { group: "Content & Creative", roles: ["Hindi / English Content Writer", "SEO & Content Strategist", "YouTube Video Editor", "Short-form Video Editor", "Motion / Graphic Designer", "Script Researcher"], note: "Turn verified business and market information into clear articles, scripts, explainers and visual stories." },
  { group: "Growth & Operations", roles: ["Growth / Digital Marketing Associate", "Community & Customer Support", "Sales / Partnerships Associate", "Product Operations Associate", "UX / Web Designer"], note: "Help improve discovery, user experience, audience communication, feedback loops and responsible partnerships." },
]

const videos = [
  { title: "LuckyMarkets — Sample Business Story", id: "SgVF44McpCU", url: "https://youtu.be/SgVF44McpCU" },
  { title: "LuckyMarkets — Sample Business Story", id: "RYjQ4eGIbOA", url: "https://youtu.be/RYjQ4eGIbOA" },
]

export default function LuckyMarketsProjectPage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <section className="relative isolate overflow-hidden border-b border-border">
        <div aria-hidden="true" className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_80%_10%,rgba(249,115,22,0.15),transparent_42%),radial-gradient(ellipse_at_10%_90%,rgba(59,130,246,0.09),transparent_40%)]" />
        <div className="mx-auto max-w-6xl px-5 pb-10 pt-8 md:px-8 md:pb-12 md:pt-10">
          <div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-border bg-card/70 px-3 py-1.5 text-xs font-medium">An UpForge initiative</span><span className="rounded-full bg-orange-500/10 px-3 py-1.5 text-xs font-semibold text-orange-600">Building · Contributor applications</span></div>
          <div className="mt-5 grid items-center gap-7 md:grid-cols-[1.25fr_0.75fr]">
            <div><Image src="/luckymarkets.jpg" alt="LuckyMarkets logo" width={88} height={88} priority className="mb-4 h-[68px] w-[68px] rounded-xl border border-border bg-white p-2 object-contain shadow-sm" /><p className="text-sm font-semibold uppercase tracking-[0.2em] text-orange-500">Understand markets. Build useful tools.</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">LuckyMarkets<span className="text-orange-500">.</span></h1><p className="mt-3 max-w-2xl text-base leading-7 text-muted-foreground">A finance education and product initiative explaining business stories and developing practical market-information experiences. We’re inviting people who want to contribute with skill, care and clear thinking.</p>
              <div className="mt-5 flex flex-wrap gap-3"><a href="#videos" className="inline-flex items-center gap-2 rounded-xl bg-foreground px-5 py-3 text-sm font-semibold text-background transition hover:-translate-y-0.5 hover:opacity-90">Watch project videos <span aria-hidden="true">↓</span></a><a href="#opportunities" className="inline-flex items-center gap-2 rounded-xl border border-border bg-card/70 px-5 py-3 text-sm font-semibold transition hover:bg-muted">Explore opportunities <span aria-hidden="true">↗</span></a></div>
            </div>
            <div className="grid grid-cols-2 gap-3 md:pb-1"><div className="rounded-2xl border border-border bg-card/80 p-4"><p className="text-xs text-muted-foreground">Focus</p><p className="mt-2 text-lg font-semibold">Finance × Media</p></div><div className="rounded-2xl border border-border bg-card/80 p-4"><p className="text-xs text-muted-foreground">Approach</p><p className="mt-2 text-lg font-semibold">Research-led</p></div><div className="col-span-2 rounded-2xl border border-orange-500/25 bg-orange-500/[0.06] p-4"><p className="text-xs font-medium text-orange-600">Contributor compensation</p><p className="mt-1 text-2xl font-bold">₹15,000–₹25,000 <span className="text-sm font-medium text-muted-foreground">per month</span></p><p className="mt-1 text-xs leading-5 text-muted-foreground">Indicative range for applicable roles; final terms depend on role scope, skills and engagement arrangement.</p></div></div>
          </div>
        </div>
      </section>

      <section id="videos" className="mx-auto max-w-6xl px-5 py-10 md:px-8 md:py-12">
        <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-orange-500">Watch before applying</p><h2 className="mt-2 text-3xl font-bold tracking-tight md:text-4xl">Get a feel for the work.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">These videos show our current communication style and project direction. Reviewing them is part of understanding the work, not a social-follow requirement.</p></div><a className="text-sm font-semibold text-orange-600 hover:underline" href="https://www.youtube.com/@LuckyMarkets" target="_blank" rel="noreferrer">Explore LuckyMarkets on YouTube ↗</a></div>
        <div className="mt-7 grid gap-5 md:grid-cols-2">{videos.map((video) => <article key={video.id} className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="aspect-video bg-black"><iframe className="h-full w-full" src={`https://www.youtube-nocookie.com/embed/${video.id}`} title={video.title} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div><div className="flex items-center justify-between gap-3 p-4"><h3 className="text-sm font-semibold">{video.title}</h3><a href={video.url} target="_blank" rel="noreferrer" className="shrink-0 text-xs font-semibold text-orange-600 hover:underline">Open ↗</a></div></article>)}</div>
        <div className="mt-4 rounded-xl border border-border bg-muted/30 p-4 text-sm leading-6 text-muted-foreground">Also explore the project’s public Instagram and YouTube presence from the official channel links. We value genuine familiarity with the content and audience; following or liking is not a selection condition.</div>
      </section>

      <section className="border-y border-border bg-muted/20">
        <div className="mx-auto max-w-6xl px-5 py-14 md:px-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-orange-500">Product roadmap</p><h2 className="mt-2 text-3xl font-bold tracking-tight">From explainers to useful experiences.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">We are exploring tools that make public market and company information easier to navigate. Roadmap concepts are under research and are not yet promises of live features.</p><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["IPO tracker & calendar", "IPO data and research tools", "Company expansion profiles", "Market dashboards & portfolio utilities"].map((item, i) => <div key={item} className="rounded-xl border border-border bg-card p-4"><span className="text-xs font-semibold text-orange-500">0{i+1}</span><p className="mt-3 font-semibold">{item}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-muted-foreground">Any market-related analysis will require transparent sourcing, methodology and appropriate disclaimers. No return or outcome is guaranteed.</p></div>
      </section>

      <section id="opportunities" className="mx-auto max-w-6xl px-5 py-10 md:px-8 md:py-12">
        <div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-orange-500">Contributor tracks</p><h2 className="mt-2 text-3xl font-bold tracking-tight md:text-4xl">Bring the skill. Help shape the role.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">These are areas we expect to need. You do not need to match a title exactly. Tell us where you can create measurable value and what you would own.</p></div>
        <div className="mt-7 grid items-start gap-4 md:grid-cols-2">{roles.map((group, i) => <details key={group.group} className="group self-start rounded-2xl border border-border bg-card p-5 transition-colors open:border-orange-500/40 open:shadow-md"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><span><span className="block text-xs font-semibold text-orange-600">TRACK 0{i+1}</span><span className="mt-1 block text-lg font-bold">{group.group}</span></span><span aria-hidden="true" className="grid size-8 shrink-0 place-items-center rounded-full border border-border text-lg transition group-open:rotate-45">+</span></summary><div className="mt-4 border-t border-border pt-4"><div className="flex flex-wrap gap-2">{group.roles.map(role => <span key={role} className="rounded-full bg-muted px-3 py-1.5 text-xs font-medium">{role}</span>)}</div><p className="mt-4 text-sm leading-6 text-muted-foreground">{group.note}</p></div></details>)}</div>
        <div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-border p-5"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Work arrangement</p><p className="mt-2 font-semibold">Remote · Hybrid · Office-based</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Available arrangement will depend on the role, location and project requirements. Confirmed details are shared during the selection discussion.</p></div><div className="rounded-2xl border border-border p-5"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Indicative monthly range</p><p className="mt-2 text-2xl font-bold">₹15k–₹25k</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Role-dependent proposed range, not a guaranteed fixed offer. Scope, experience and terms will be discussed before any engagement.</p></div></div>
      </section>

      <section className="mx-auto max-w-6xl px-5 pb-16 md:px-8"><div className="rounded-3xl bg-foreground p-6 text-background md:p-10"><div className="grid gap-8 md:grid-cols-[1fr_0.85fr] md:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-orange-400">How to be considered</p><h2 className="mt-2 text-3xl font-bold">Show us how you think.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-background/70">Review the brief and videos, then send a considered proposal in your own words. Specific, honest thinking matters more than polished generic language.</p></div><div className="rounded-2xl border border-background/15 bg-background/[0.06] p-5"><ol className="space-y-3 text-sm"><li><span className="mr-2 text-orange-400">01</span> Your strongest skill area and relevant work</li><li><span className="mr-2 text-orange-400">02</span> A practical contribution you could own</li><li><span className="mr-2 text-orange-400">03</span> Your availability and preferred work arrangement</li><li><span className="mr-2 text-orange-400">04</span> Submit within 7 days of the invitation email</li></ol><a href="mailto:team@upforge.org?subject=LuckyMarkets%20Contributor%20Proposal" className="mt-5 inline-flex w-full items-center justify-center rounded-xl bg-orange-500 px-5 py-3 text-sm font-bold text-white transition hover:bg-orange-600">Send proposal to team@upforge.org ↗</a></div></div><p className="mt-6 border-t border-background/15 pt-5 text-xs leading-5 text-background/60">Initial review considers relevance, demonstrated ability and the substance of your response. Complete role description, responsibilities, confirmed compensation and work arrangement, engagement terms and next steps will be shared with candidates invited to proceed. No application fee is charged by UpForge for submitting interest.</p></div><p className="mt-5 text-xs leading-5 text-muted-foreground">LuckyMarkets is an educational and informational initiative. It does not promise investment returns or guaranteed employment. Engagement is subject to role fit and mutually agreed terms.</p></section>
    </main>
  )
}
